"""Prompt module for WeakAgent."""

from .brief_react import THINK_NEXT_STEP_PROMPT, THINK_SYSTEM_PROMPT, ACT_NEXT_STEP_PROMPT, ACT_SYSTEM_PROMPT

__all__ = ["THINK_NEXT_STEP_PROMPT", "THINK_SYSTEM_PROMPT", "ACT_NEXT_STEP_PROMPT", "ACT_SYSTEM_PROMPT"]