# Global LLM configuration
[llm]
model = "qwen-plus"       # The LLM model to use
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1" # API endpoint URL
api_key = "sk-4f519a5d8cba44c48ad3655926cfc753"                   # Your API key
max_tokens = 8192                          # Maximum number of tokens in the response
temperature = 0.0                          # Controls randomness
supports_images = false
use_max_completion_tokens = false

# [llm] #OLLAMA:
# api_type = 'ollama'
# model = "llama3.2"
# base_url = "http://localhost:11434/v1"
# api_key = "ollama"
# max_tokens = 4096
# temperature = 0.0

[llm.fast]
model = "qwen-plus"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "sk-4f519a5d8cba44c48ad3655926cfc753"
max_tokens = 4096
temperature = 0.0
supports_images = true
use_max_completion_tokens = true

# Optional configuration for specific LLM models
[llm.vision]
model = "claude-3-7-sonnet-20250219"       # The vision model to use
base_url = "https://api.anthropic.com/v1/" # API endpoint URL for vision model
api_key = "YOUR_API_KEY"                   # Your API key for vision model
max_tokens = 8192                          # Maximum number of tokens in the response
temperature = 0.0                          # Controls randomness for vision model